### ISSUE TITLE
License for this repo

### ISSUE THREAD

**Issue by hlml** [Joshua-Ren/Neural_Iterated_Learning#4]
Hi Joshua,

Thanks for this very interesting paper and releasing the code. Since there isn't a license in this repo, would you be opposed to me releasing code that builds on top of the repo? Alternatively, you can add a license to the repo (similar to https://github.com/allenai/hidden-networks/blob/master/LICENSE) if you'd like!

Thanks!
Hattie

**Comment by Joshua-Ren** [comment]
Hi Hattie,

Thanks very much for your email. I add a license to that repo (sorry for
doing this so late). Feel free to release the code of your project.

Cheers,

Joshua

Hattie Zhou ***@***.***> 于2021年10月14日周四 下午10:56写道：

**Comment by hlml** [comment]
Thanks so much Joshua!
